### ISSUE TITLE
Fails to create folders using postgres db and additional resources

### ISSUE THREAD

**Issue by Mrls94** [grafana/terraform-provider-grafana#1910]
### Terraform Version

1.9.4

### Terraform Grafana Provider Version

3.13.1

### Grafana Version

11.3.0

### Affected Resource(s)

* grafana_folder

### Terraform Configuration Files

Terraform file:
```hcl
terraform {
  required_version = ">= 1.3"

  required_providers {
    grafana = {
      source  = "grafana/grafana"
      version = ">= 2"
    }
  }
}

provider "grafana" {
  url  = "http://localhost:3000" 
  auth = "admin:notrealpassword"
}

locals {
  org_id = 1

  main_region = "us-east-1"
  prometheus_domain = "someprometheusurl" 
  loki_domain = "somelokiurl"
}

resource "grafana_data_source" "prometheus" {
  type = "prometheus"
  name = "prom1"
  is_default = true
  url = "https://${local.prometheus_domain}"
}

resource "grafana_data_source" "loki" {
  type = "loki"
  name = "loki1"
  is_default = false
  url = "https://${local.loki_domain}"
}

resource "grafana_data_source" "cloudwatch" {
  type = "cloudwatch"
  name = "cloudwatch1"
  is_default = false
  json_data_encoded = jsonencode({
    defaultRegion = local.main_region
    authType      = "default"
  }) 
}

## Folders

resource "grafana_folder" "folder1" {
  title = "folder with spaces"
}

resource "grafana_folder" "folder2" {
  title = "folder with spaces again"
}

## Alerts

locals{
  probes = {
    jenkins_probe = {
      url = "https://someurltoprobe1"
      folder_uid = grafana_folder.folder1.uid
      name = "some probe"
      summary = "some url is failing to return successful status code"
      pending_period = "45m"
    }
    monitoring_probe = {
      url = "https://someurltoprobe2"
      folder_uid = grafana_folder.folder2.uid
      name = "some probe"
      summary = "some url is failing to return successful status code"
      pending_period = "15m"
    }
  }
}

resource "grafana_rule_group" "probes" {
  for_each = local.probes

  org_id           = 1
  name             = each.value.name
  folder_uid       = each.value.folder_uid
  interval_seconds = 300

  rule {
    name      = each.value.name
    condition = "C"

    data {
      ref_id = "A"

      relative_time_range {
        from = 300
        to   = 0
      }

      datasource_uid = grafana_data_source.prometheus.uid
      model          = "{\"datasource\":{\"type\":\"prometheus\",\"uid\":\"${grafana_data_source.prometheus.uid}\"},\"disableTextWrap\":false,\"editorMode\":\"builder\",\"expr\":\"probe_success{instance=\\\"${each.value.url}\\\"}\",\"fullMetaSearch\":false,\"includeNullMetadata\":true,\"instant\":true,\"intervalMs\":1000,\"legendFormat\":\"__auto\",\"maxDataPoints\":43200,\"range\":false,\"refId\":\"A\",\"useBackend\":false}"
    }
    data {
      ref_id = "C"

      relative_time_range {
        from = 300
        to   = 0
      }

      datasource_uid = "__expr__"
      model          = "{\"conditions\":[{\"evaluator\":{\"params\":[1],\"type\":\"lt\"},\"operator\":{\"type\":\"and\"},\"query\":{\"params\":[\"C\"]},\"reducer\":{\"params\":[],\"type\":\"last\"},\"type\":\"query\"}],\"datasource\":{\"type\":\"__expr__\",\"uid\":\"__expr__\"},\"expression\":\"A\",\"intervalMs\":1000,\"maxDataPoints\":43200,\"refId\":\"C\",\"type\":\"threshold\"}"
    }

    no_data_state  = "NoData"
    exec_err_state = "Error"
    for            = each.value.pending_period
    annotations = {
      description = ""
      summary     = each.value.summary
    }
    labels = {
      "" = ""
    }
    is_paused = false
  }
}

resource "grafana_contact_point" "test_channel" {
  name = "test Channel"

  teams {
    disable_resolve_message = true
    url                     = "https://somehookurl"
  }

  lifecycle {
    create_before_destroy = true
  }
}

resource "grafana_notification_policy" "notification_policy_1" {
  contact_point = grafana_contact_point.test_channel.name
  group_by      = ["workload"]

  repeat_interval = "1d"
}

resource "grafana_team" "team1" {
  name = "team1"
}

resource "grafana_team" "team2" {
  name = "team2"
}

resource "grafana_folder_permission" "folder_permissions" {
  folder_uid = grafana_folder.folder1.uid

  permissions {
    team_id    = grafana_team.team1.id
    permission = "Edit"
  }
}

```

Docker compose file:
```yaml
services:
  grafana:
    image: docker.io/grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=notrealpassword
      - GF_DATABASE_TYPE=postgres
      - GF_DATABASE_HOST=db:5432
      - GF_DATABASE_USER=grafana
      - GF_DATABASE_PASSWORD=mysecretpassword
      - GF_DATABASE_NAME=grafana
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
        restart: true
  db:
    image: docker.io/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U grafana -d grafana"]
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=grafana
      - POSTGRES_DB=grafana
    ports:
      - 5432:5432

```

### Expected Behavior

Plan should have executed fully. 

### Actual Behavior

received following errors:

```
╷
│ Error: failed to create folder: [POST /folders][409] createFolderConflict {"message":"a folder with the same name already exists in the current location"}
│
│   with grafana_folder.folder1,
│   on grafana-config.tf line 51, in resource "grafana_folder" "folder1":
│   51: resource "grafana_folder" "folder1" {
│
╵
╷
│ Error: failed to create folder: [POST /folders][409] createFolderConflict {"message":"a folder with the same name already exists in the current location"}
│
│   with grafana_folder.folder2,
│   on grafana-config.tf line 55, in resource "grafana_folder" "folder2":
│   55: resource "grafana_folder" "folder2" {
│
```

### Steps to Reproduce

use the docker compose file to start up grafana and postgres then execute terraform

1. docker-compose up
2. terraform apply

I noticed when changing the folder names to "folder1" and "folder2" the plan applies succesfully.
