### ISSUE TITLE
Cloudwatch scrape job does not like IOPS case

### ISSUE THREAD

**Issue by sophie-warner-annalise-ai** [grafana/terraform-provider-grafana#2186]
### Terraform Version

OpenTofu v1.9.0

### Terraform Grafana Provider Version

v3.25.0

### Grafana Version

cloud - steady

### Affected Resource(s)

* grafana_cloud_provider_aws_cloudwatch_scrape_job

### Terraform Configuration Files

```hcl
locals {
  metrics = yamldecode(file("${path.module}/metrics.yaml"))
}

resource "grafana_cloud_provider_aws_cloudwatch_scrape_job" "this" {
  stack_id                = var.stack_id
  name                    = "${var.name}-cloudwatch-scrape-job"
  aws_account_resource_id = grafana_cloud_provider_aws_account.this.resource_id
  enabled              = true

  dynamic "service" {
    for_each = local.metrics["services"]
    iterator = s
    content {
      name = s.value["name"]
      scrape_interval_seconds = s.value["scrape_interval_seconds"]
      dynamic "metric" {
        for_each = s.value["metrics"]
        content {
          name       = metric.value["name"]
          statistics = metric.value["statistics"]
        }
      }
    }
  }
}
```

```yaml
services:
  - name: AWS/DocDB
    scrape_interval_seconds: 300
    metrics:
    - name: VolumeReadIOPS
      statistics: 
        - Average
    - name: VolumeWriteIOPS
      statistics: 
        - Average
...
```

### Expected Behavior

Applied without errors

### Actual Behavior

Applies but provides this error

```
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to module.cloud_watch_staging.grafana_cloud_provider_aws_cloudwatch_scrape_job.this, provider "provider[\"registry.opentofu.org/grafana/grafana\"].annalise-dev-au" produced an unexpected new
│ value: .service[0].metric[26].name: was cty.StringVal("VolumeWriteIOPS"), but now cty.StringVal("VolumeWriteIOPs").
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

### Steps to Reproduce

`tofu apply`

### Important Factoids

If I change the metric to be `VolumeWriteIOPs` it does not complain. However, the case is generally IOPS?
