### ISSUE TITLE
Support Loki derived fields in jsonData

### ISSUE THREAD

**Issue by techgnosis** [grafana/terraform-provider-grafana#375]
The provider already provides lots of options for creating data sources but there is some key functionality missing for Loki. Loki lets you create "derived fields" and then link from those fields to a URL. This is usually used to find a trace ID in a log line and then link to Tempo or Jaeger. 

https://grafana.com/docs/grafana/latest/datasources/loki/#derived-fields

Here are some examples from a provisioning file

```
jsonData:
        maxLines: 1000
        derivedFields:
        - datasourceUid: jaeger-ds
          matcherRegex: .*(?:jaeger_trace_id=|jaeger_trace_id\":\s*\")(.*?)(?:\"|\s).*
          name: "JaegerTraceId"
          url: "$${__value.raw}"
        - datasourceUid: zipkin-ds
          matcherRegex: .*(?:zipkin_trace_id=|zipkin_trace_id\":\s*\")(.*?)(?:\"|\s).*
          name: "ZipkinTraceId"
          url: "$${__value.raw}"
        - datasourceUid: tempo
          matcherRegex: .*(?:tempo_trace_id=|tempo_trace_id\":\s*\")(.*?)(?:\"|\s).*
          name: "TempoTraceId"
          url: "$${__value.raw}"
        - datasourceUid: tempo
          matcherRegex: (?:traceID|trace_id)=(\w+)
          name: "TraceID"
          url: $${__value.raw}
```
