### ISSUE TITLE
Import via grafana.com

### ISSUE THREAD

**Issue by francardoso93** [grafana/terraform-provider-grafana#443]
Is it possible to import `grafana.com` dashboard through URL or ID like we do through the UI or API `/api/dashboards/import`?

Is this an existing feature? How to do it?
If no: That's the feature request 
If yes: Lack of docs

**Comment by inkel** [comment]
Hi @francardoso93, thanks for the interest in the provider and sorry for the long delay in answering.

I'm trying to understand what you mean by this. You think something like the following?

```
terraform import grafana_dashboard.example http://yourcloudaccount.grafana.net/d/d4shB04rD/example-dashboard
```

(BTW, this doesn't work).

What **do** work is configuring the provider to use your cloud account and then use `terraform import` as stated in the [import documentation](https://registry.terraform.io/providers/grafana/grafana/latest/docs/resources/dashboard#import) for dashboards:

```terraform
provider "grafana" {
  cloud_api_key = "your-grafana-cloud-api-key"
}

resource "grafana_dashboard" "example" {
  config_json = file("dashboard.json")
}
```

Then you can do `terraform import grafana_dashboard.example your-grafana-cloud-dashboard-id` and that should import it **into Terraform state**. You would still need to download the dashboard's JSON model into `dashboard.json` otherwise if you run `terraform plan|apply` again you will see drift.

If what you meant was importing Terraform configurations (e.g. having `terraform` generating the `.tf` file) then the answer is no, that doesn't work and it probably won't work in the foreseeable future, as it's out of the scope of both Terraform and the provider.

**Comment by Hronom** [comment]
It's not about terraform import mechanisms it's about importing Grafana dashboard from Grafana dashboards marketplace https://grafana.com/grafana/dashboards/ 

When you provision Grafana, in configuration you can define this:
```
  dashboards:
    default:
    istio:
      istio-control-plane-dashboard:
        gnetId: 7645
        revision: 158
        datasource: Prometheus
      istio-mesh-dashboard:
        gnetId: 7639
        revision: 158
        datasource: Prometheus
      istio-service-dashboard:
        gnetId: 7636
        revision: 158
        datasource: Prometheus
      istio-workload-dashboard:
        gnetId: 7630
        revision: 158
        datasource: Prometheus
      istio-performance-dashboard:
        gnetId: 11829
        revision: 158
        datasource: Prometheus
      istio-wasm-extension-dashboard:
        gnetId: 13277
        revision: 115
        datasource: Prometheus
```
where `gnetId` is id of Dashboard on marketplace and `revision` is the revision number of that dashboard.
For example check `Istio Control Plane Dashboard`: https://grafana.com/grafana/dashboards/7645-istio-control-plane-dashboard/?tab=revisions

But this approach has limit - it's only works with self-managed Grafana instance, if you work with Grafana Cloud you cannot use it.

With Grafana Cloud you can use terraform provider or crossplane provider for provisioning Grafana alerts, dashboards etc.

Expectation is to have in Grafana terraform provider possibility to import dashboard not only using `config_json` field but something like `gnetId` and `revision` fields.

So you can import transparently dashboards from that marketplace to your self-managed instance of Grafana or in Grafana Cloud.

From my side I'm also looking for the same functionality for crossplane provider too: https://github.com/grafana/crossplane-provider-grafana

Please re-open this, I think terraform provider should support [Grafana dashboards marketplace](https://grafana.com/grafana/dashboards/).

**Comment by Hronom** [comment]
@inkel It's not about terraform import mechanisms it's about importing Grafana dashboard from [Grafana dashboards marketplace](https://grafana.com/grafana/dashboards/). 

When you provision Grafana, in configuration you can define this:
```
  dashboards:
    default:
    istio:
      istio-control-plane-dashboard:
        gnetId: 7645
        revision: 158
        datasource: Prometheus
      istio-mesh-dashboard:
        gnetId: 7639
        revision: 158
        datasource: Prometheus
      istio-service-dashboard:
        gnetId: 7636
        revision: 158
        datasource: Prometheus
      istio-workload-dashboard:
        gnetId: 7630
        revision: 158
        datasource: Prometheus
      istio-performance-dashboard:
        gnetId: 11829
        revision: 158
        datasource: Prometheus
      istio-wasm-extension-dashboard:
        gnetId: 13277
        revision: 115
        datasource: Prometheus
```
where `gnetId` is id of Dashboard on marketplace and `revision` is the revision number of that dashboard.
For example check `Istio Control Plane Dashboard`: https://grafana.com/grafana/dashboards/7645-istio-control-plane-dashboard/?tab=revisions

But this approach has limit - it's only works with self-managed Grafana instance, if you work with Grafana Cloud you cannot use it.

With Grafana Cloud you can use terraform provider or crossplane provider for provisioning Grafana alerts, dashboards etc.

Expectation is to have in Grafana terraform provider possibility to import dashboard not only using `config_json` field but something like `gnetId` and `revision` fields.
So end user of this provider can use one of two options:
1. `config_json` field
2. `gnetId` + `revision` fields

I understand that I can use now as workaround `config_json`, but from user experience it will be nice if I can use `gnetId` + `revision` instead.

So you can import in the same way dashboards from [Grafana dashboards marketplace](https://grafana.com/grafana/dashboards/) to your self-managed Grafana instance or Grafana Cloud.

From my side I'm also looking for the same functionality for crossplane provider too: https://github.com/grafana/crossplane-provider-grafana . 
But I believe all from terraform provider will be automatically ported there.

Please re-open this, I think terraform provider should support [Grafana dashboards marketplace](https://grafana.com/grafana/dashboards/).
